//
using SASZombieAssaultTD.Engine.Diagnostics;

//File:    GlobalSuppressions.cs
//Purpose: Global compiler warning suppression directives for engine stability.
//         Contains intentional suppressions for known compiler warnings across the codebase.

//Architecture:
//- Assembly-level compiler warning suppressions
//- Intentional unused field suppressions for engine subsystems
//- Reflection and serialization field assignment suppressions
//- Future feature reservation suppressions
//- Legacy code path nullable annotation suppressions
//- Build output cleanliness and runtime stability

//Usage:
//    // Automatically applied to all engine code
//    // No direct usage required
////

// <auto-generated>
// This file contains global suppression directives for compiler warnings
// that are known, intentional, and safe across the engine codebase.
// These suppressions keep build output clean while preserving
// subsystem-level diagnostics and runtime stability.
// </auto-generated>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Compiler", "CS0414", Justification = "Intentional unused private fields in engine subsystems")]
[assembly: SuppressMessage("Compiler", "CS0649", Justification = "Fields assigned via reflection, serialization, or external systems")]
[assembly: SuppressMessage("Compiler", "CS0169", Justification = "Unused private fields reserved for future engine features")]
[assembly: SuppressMessage("Compiler", "CS0067", Justification = "Events intentionally declared for future subscription patterns")]
[assembly: SuppressMessage("Compiler", "CS8632", Justification = "Nullable annotations appear in legacy or transitional code paths")]
