flowchart TD



    A[Program.cs] -->
    B{Exit Requested?}
    B -->|Yes| Shutdown[Shutdown.cs]
    B -->|No| C[GameLoop.cs]
    C --> D{Is Rendering Needed?}

    D -->|Yes| F[RenderQueueFrontend.cs, RenderQueue.cs, RenderItem.cs,
     Framebuffer.cs, IRenderContext.cs, GameLoop.cs]
     D -->|No| G[Idle.cs, UserQuit, OSQuit, LogicQuit, FatalQuit]
     F --> Rendering[Rendering Ended] --> B
        G --> Idle[Idle Ended] --> B

        


     

    classDef red fill:#ff444d,stroke:#b30000,color:#000;
    classDef blue fill:#439dff,stroke:#0033cc,color:#000;
    classDef green fill:#33cc33,stroke:#17a11f,color:#000;
    classDef brown fill:#b55c1d,stroke:#5a2d0c,color:#000;
    classDef yellow fill:#ffe066,stroke:#cc9900,color:#000;
    classDef orange fill:#ff9966,stroke:#cc6600,color:#000;
    classDef purple fill:#b366ff,stroke:#6600cc,color:#000;
    classDef grey fill:#d9d9d9,stroke:#a6a6a6,color:#000;
    classDef lightblue fill:#a7c7e7,stroke:#b30000,color:#000;

    class A green;
    class B green;
    class C orange;
    class D purple;
    class F blue;
    class G brown;
    class Rendering blue;
    class Idle brown;
    class Shutdown grey;