// ====================================================================================================
//  FILE: MigrationAnalysisResult.cs
//  PATH: ./Engine/Navigation/
//  SUBSYSTEM: Navigation
//
//  ROLE:
//      Provides deterministic result structures for Navigation subsystem migration analysis. This file
//      contains the data model used to summarize ECSEntityCore migration counts, percentages, and
//      recommendations produced by NavigationMigrationHelper.
//
//  RESPONSIBILITIES:
//      - Represent pure data outcomes from migration analysis routines.
//      - Store ECSEntityCore counts, migration percentages, and analysis flags.
//      - Provide a deterministic container for recommendations generated by migration validators.
//
//  NON-RESPONSIBILITIES:
//      - Executing migration logic or performing validation itself.
//      - Managing engine state, subsystem orchestration, or runtime sequencing.
//      - Performing navigation or pathfinding operations.
//
//  NOTES:
//      Navigation result classes are lightweight containers used by Navigation subsystem programs.
//      This header is a template updated to match the purpose of this Navigation result file.
// ====================================================================================================

using System.Collections.Generic;
namespace SASZombieAssaultTD.Engine.Navigation

{
    //=====================================================================
    //SUPPORTING TYPES
    //=====================================================================

    /// <summary>
    /// Stores validation results for migration checks.
    /// </summary>

    /// <summary>
    /// Stores migration analysis statistics and recommendations.
    /// </summary>
    public sealed class MigrationAnalysisResult
    {
        public MigrationAnalysisResult()
        { }

        public int TotalEntities { get; set; }
        public int MigratedEntities { get; set; }
        public float MigrationPercentage { get; set; }
        public bool FullyMigrated { get; set; }
        public List<string> Recommendations { get; } = new();
    }
}
