/*
File:    AnimationSystem.cs
Purpose: P11-16-05 - System for managing animation playback and state machines.
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This xml documentation was generated by CXCommenter: 1.0.1.0.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="AnimationSystem.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
using SASZombieAssaultTD.Engine.Animation.Components;
using SASZombieAssaultTD.Engine.Animation.Events;
using SASZombieAssaultTD.Engine.Animation.Core;
using SASZombieAssaultTD.Engine.ECS;
using System;
using System.Collections.Generic;
using SASZombieAssaultTD.Engine.Core;
using DamageComponent = SASZombieAssaultTD.Engine.Components.DamageComponent;

/// <summary>
///       Namespace Name - SASZombieAssaultTD.Engine.Animation.Systems.
/// </summary>
namespace SASZombieAssaultTD.Engine.Animation.Systems
{
    public sealed class AnimationSystem : ISystem
    {


        /// <summary>
        ///      Property Name - IsEnabled.
        ///  </summary>
        public bool IsEnabled { get; private set; } = true;


        /// <summary>
        ///      Property Name - IsInitialized.
        ///  </summary>
        public bool IsInitialized { get; private set; } = false;


        /// <summary>
        ///      Property Name - Priority.
        ///  </summary>
        public SystemPriority Priority { get; private set; } = SystemPriority.Normal;


        /// <summary>
        ///      Property Name - LastUpdateTime.
        ///  </summary>
        public float LastUpdateTime { get; private set; } = 0f;


        /// <summary>
        ///      Property Name - UpdateCount.
        ///  </summary>
        public uint UpdateCount { get; private set; } = 0;

        private readonly ECSWorld _ecsWorld;
        private readonly Dictionary<uint, AnimationControllerComponent> _animationControllers = new();
        private readonly Dictionary<uint, AnimationStateMachine> _stateMachines = new();
        private int _entitiesProcessed;
        private float _totalAnimationTime;
        private int _clipsUpdated;
        private int _statesUpdated;
        private int _transitionsTriggered;



        /// <summary>
        ///      Property Name - EntitiesProcessed.
        ///  </summary>
        public int EntitiesProcessed => _entitiesProcessed;


        /// <summary>
        ///      Property Name - TotalAnimationTime.
        ///  </summary>
        public float TotalAnimationTime => _totalAnimationTime;


        /// <summary>
        ///      Property Name - ClipsUpdated.
        ///  </summary>
        public int ClipsUpdated => _clipsUpdated;


        /// <summary>
        ///      Property Name - StatesUpdated.
        ///  </summary>
        public int StatesUpdated => _statesUpdated;


        /// <summary>
        ///      Property Name - TransitionsTriggered.
        ///  </summary>
        public int TransitionsTriggered => _transitionsTriggered;

        public event Action<AnimationControllerComponent, string>? OnAnimationStarted;
        public event Action<AnimationControllerComponent, string>? OnAnimationCompleted;
        public event Action<AnimationControllerComponent, AnimationEvent>? OnAnimationEventFired;
#pragma warning disable CS0067 // Event is never used
        public event Action<AnimationStateMachine, AnimationTransition, object>? OnStateMachineTransition;
#pragma warning restore CS0067



        /// <summary>
        ///  Function Name :  AnimationSystem.
        /// </summary>
        /// <param name="ecsWorld">This ecsWorld's Datatype is : SASZombieAssaultTD.Engine.ECS.ECSWorld.</param>
        /// <returns>void.</returns>
        public AnimationSystem(ECSWorld ecsWorld)
        {
            _ecsWorld = ecsWorld ?? throw new ArgumentNullException(nameof(ecsWorld));
            ModernLoggingSystem.Log("INFO", "AnimationSystem: Initialized");
        }



        /// <summary>
        ///  Function Name :  Initialize.
        /// </summary>
        /// <returns>void.</returns>
        public void Initialize()
        {
            if (IsInitialized) return;
            IsInitialized = true;
            ModernLoggingSystem.Log("INFO", "AnimationSystem: System initialized");
        }



        /// <summary>
        ///  Function Name :  Update.
        /// </summary>
        /// <param name="deltaTime">This deltaTime's Datatype is : float.</param>
        /// <returns>void.</returns>
        public void Update(float deltaTime)
        {
            if (!IsEnabled || !IsInitialized) return;

            ResetFrameStats(deltaTime);

            try
            {
                UpdateAnimationControllers(deltaTime);
                UpdateStateMachines(deltaTime);
                UpdateRenderableComponents();

                ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Processed {_entitiesProcessed} entities, {_totalAnimationTime:F3}s total animation time");
            }
            catch (Exception ex)
            {
                ModernLoggingSystem.Log("ERROR", $"AnimationSystem: Error during update: {ex.Message}");
            }
        }



        /// <summary>
        ///  Function Name :  ResetFrameStats.
        /// </summary>
        /// <param name="deltaTime">This deltaTime's Datatype is : float.</param>
        /// <returns>void.</returns>
        private void ResetFrameStats(float deltaTime)
        {
            UpdateCount++;
            LastUpdateTime = deltaTime;
            _entitiesProcessed = 0;
            _totalAnimationTime = 0f;
            _clipsUpdated = 0;
            _statesUpdated = 0;
            _transitionsTriggered = 0;
        }



        /// <summary>
        ///  Function Name :  UpdateAnimationControllers.
        /// </summary>
        /// <param name="deltaTime">This deltaTime's Datatype is : float.</param>
        /// <returns>void.</returns>
        private void UpdateAnimationControllers(float deltaTime)
        {
            foreach (var entity in _ecsWorld.GetEntitiesWith<AnimationControllerComponent>())
            {
                var controller = entity.GetComponent<AnimationControllerComponent>();
                if (controller == null) continue;

                var previousTime = controller.PlaybackTime;
                var previousClip = controller.CurrentClip;

                controller.Update(deltaTime);
                _totalAnimationTime += deltaTime;
                _clipsUpdated++;
                _entitiesProcessed++;

                FireAnimationEvents(controller, previousTime, previousClip);
            }
        }



        /// <summary>
        ///  Function Name :  FireAnimationEvents.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="previousTime">This previousTime's Datatype is : float.</param>
        /// <param name="previousClip">This previousClip's Datatype is : string.</param>
        /// <returns>void.</returns>
        private void FireAnimationEvents(AnimationControllerComponent controller, float previousTime, string? previousClip)
        {
            var currentClip = controller.CurrentClip;
            var currentTime = controller.PlaybackTime;
            var clip = GetClip(currentClip);

            if (previousClip != currentClip && !string.IsNullOrEmpty(currentClip))
            {
                OnAnimationStarted?.Invoke(controller, currentClip);
                ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Entity {controller.Entity.Id} started animation '{currentClip}'");
            }

            if (previousClip == currentClip && clip != null && currentTime >= clip.Duration)
            {
                OnAnimationCompleted?.Invoke(controller, currentClip);
                ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Entity {controller.Entity.Id} completed animation '{currentClip}'");
            }

            if (clip == null) return;

            foreach (var animationEvent in clip.Events)
            {
                if (EventCrossed(controller, animationEvent, previousTime, currentTime) && !HasEventFired(controller, animationEvent))
                {
                    OnAnimationEventFired?.Invoke(controller, animationEvent);
                    MarkEventFired(controller, animationEvent);
                    ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Entity {controller.Entity.Id} fired event '{animationEvent.EventName}' at time {animationEvent.Timestamp:F3}");
                    HandleGameplayCallbacks(controller, animationEvent);
                }
            }
        }



        /// <summary>
        ///  Function Name :  EventCrossed.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <param name="previousTime">This previousTime's Datatype is : float.</param>
        /// <param name="currentTime">This currentTime's Datatype is : float.</param>
        /// <returns>bool.</returns>
        private static bool EventCrossed(AnimationControllerComponent controller, AnimationEvent animationEvent, float previousTime, float currentTime)
        {
            return controller.Speed >= 0
                ? previousTime < animationEvent.Timestamp && currentTime >= animationEvent.Timestamp
                : previousTime > animationEvent.Timestamp && currentTime <= animationEvent.Timestamp;
        }



        /// <summary>
        ///  Function Name :  HasEventFired.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <returns>bool.</returns>
        private bool HasEventFired(AnimationControllerComponent controller, AnimationEvent animationEvent)
        {
            var eventKey = $"{animationEvent.EventName}_{animationEvent.Timestamp}";
            return controller.HasParameter(eventKey);
        }



        /// <summary>
        ///  Function Name :  MarkEventFired.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <returns>void.</returns>
        private void MarkEventFired(AnimationControllerComponent controller, AnimationEvent animationEvent)
        {
            var eventKey = $"{animationEvent.EventName}_{animationEvent.Timestamp}";
            controller.SetParameter(eventKey, 1f);
        }



        /// <summary>
        ///  Function Name :  HandleGameplayCallbacks.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <returns>void.</returns>
        private void HandleGameplayCallbacks(AnimationControllerComponent controller, AnimationEvent animationEvent)
        {
            switch (animationEvent.EventName)
            {
                case "FireWeapon":
                    HandleFireWeaponEvent(controller, animationEvent);
                    break;
                case "Footstep":
                    HandleFootstepEvent(controller, animationEvent);
                    break;
                case "PlaySound":
                    HandlePlaySoundEvent(controller, animationEvent);
                    break;
                case "SpawnEffect":
                    HandleSpawnEffectEvent(controller, animationEvent);
                    break;
                case "DamageArea":
                    HandleDamageAreaEvent(controller, animationEvent);
                    break;
                default:
                    ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: No specific handler for event '{animationEvent.EventName}'");
                    break;
            }
        }



        /// <summary>
        ///  Function Name :  HandleFireWeaponEvent.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <returns>void.</returns>
        private void HandleFireWeaponEvent(AnimationControllerComponent controller, AnimationEvent animationEvent)
        {
            var damage = animationEvent.GetParameter<float>("Damage");
            if (damage.Equals(default(float))) damage = 10f;
            var damageComponent = new DamageComponent { Damage = damage };
            controller.Entity.AddComponent(damageComponent);
            ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Entity {controller.Entity.Id} fired weapon for {damage} damage");
        }



        /// <summary>
        ///  Function Name :  HandleFootstepEvent.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <returns>void.</returns>
        private void HandleFootstepEvent(AnimationControllerComponent controller, AnimationEvent animationEvent)
        {
            var soundName = animationEvent.GetParameter<string>("Sound");
            if (string.IsNullOrEmpty(soundName)) soundName = "footstep";
            ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Entity {controller.Entity.Id} footstep sound '{soundName}'");
        }



        /// <summary>
        ///  Function Name :  HandlePlaySoundEvent.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <returns>void.</returns>
        private void HandlePlaySoundEvent(AnimationControllerComponent controller, AnimationEvent animationEvent)
        {
            var soundName = animationEvent.GetParameter<string>("SoundName");
            if (string.IsNullOrEmpty(soundName)) soundName = "unknown";
            ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Entity {controller.Entity.Id} playing sound '{soundName}'");
        }



        /// <summary>
        ///  Function Name :  HandleSpawnEffectEvent.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <returns>void.</returns>
        private void HandleSpawnEffectEvent(AnimationControllerComponent controller, AnimationEvent animationEvent)
        {
            var effectType = animationEvent.GetParameter<string>("EffectType");
            if (string.IsNullOrEmpty(effectType)) effectType = "default";
            ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Entity {controller.Entity.Id} spawning effect '{effectType}'");
        }



        /// <summary>
        ///  Function Name :  HandleDamageAreaEvent.
        /// </summary>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <param name="animationEvent">This animationEvent's Datatype is : SASZombieAssaultTD.Engine.Animation.Events.AnimationEvent.</param>
        /// <returns>void.</returns>
        private void HandleDamageAreaEvent(AnimationControllerComponent controller, AnimationEvent animationEvent)
        {
            var damage = animationEvent.GetParameter<float>("Damage");
            if (damage.Equals(default(float))) damage = 25f;
            var damageComponent = new DamageComponent { Damage = damage };
            controller.Entity.AddComponent(damageComponent);
            ModernLoggingSystem.Log("DEBUG", $"AnimationSystem: Entity {controller.Entity.Id} created area damage: {damage}");
        }



        /// <summary>
        ///  Function Name :  UpdateStateMachines.
        /// </summary>
        /// <param name="deltaTime">This deltaTime's Datatype is : float.</param>
        /// <returns>void.</returns>
        private void UpdateStateMachines(float deltaTime)
        {
            foreach (var entity in _ecsWorld.GetEntitiesWith<AnimationStateMachineComponent>())
            {
                var stateMachine = entity.GetComponent<AnimationStateMachineComponent>();
                if (stateMachine != null && stateMachine.IsRunning)
                {
                    stateMachine.Update(deltaTime);
                }
            }
        }



        /// <summary>
        ///  Function Name :  UpdateRenderableComponents.
        /// </summary>
        /// <returns>void.</returns>
        private void UpdateRenderableComponents()
        {
            foreach (var entity in _ecsWorld.GetEntitiesWith<ECS.SpriteComponent>())
            {
                var renderable = entity.GetComponent<ECS.SpriteComponent>();
                var animationController = entity.GetComponent<AnimationControllerComponent>();

                if (animationController != null)
                {
                    UpdateRenderableFromController(renderable, animationController);
                }
            }
        }



        /// <summary>
        ///  Function Name :  UpdateRenderableFromController.
        /// </summary>
        /// <param name="renderable">This renderable's Datatype is : SASZombieAssaultTD.Engine.ECS.SpriteComponent.</param>
        /// <param name="controller">This controller's Datatype is : SASZombieAssaultTD.Engine.Animation.Components.AnimationControllerComponent.</param>
        /// <returns>void.</returns>
        private void UpdateRenderableFromController(ECS.SpriteComponent renderable, AnimationControllerComponent controller)
        {
            var currentClip = controller.GetCurrentClip();
            if (currentClip == null) return;

            renderable.SpriteIndex = controller.GetCurrentSpriteIndex() ?? renderable.SpriteIndex;
            renderable.TransformOffset = controller.GetCurrentTransformOffset();
            var colorTint = controller.GetCurrentColorTint();
            renderable.ColorTint = new SASZombieAssaultTD.Engine.Core.Color(colorTint);
            renderable.AnimationTime = controller.PlaybackTime;
        }



        /// <summary>
        ///  Function Name :  GetClip.
        /// </summary>
        /// <param name="clipName">This clipName's Datatype is : string.</param>
        /// <returns>SASZombieAssaultTD.Engine.Animation.Core.AnimationClip.</returns>
        public AnimationClip? GetClip(string clipName)
        {
            return new AnimationClip(clipName, 1.0f, false);
        }



        /// <summary>
        ///  Function Name :  FixedUpdate.
        /// </summary>
        /// <param name="fixedDeltaTime">This fixedDeltaTime's Datatype is : float.</param>
        /// <returns>void.</returns>
        public void FixedUpdate(float fixedDeltaTime)
        {
            if (!IsEnabled || !IsInitialized) return;
        }



        /// <summary>
        ///  Function Name :  LateUpdate.
        /// </summary>
        /// <param name="deltaTime">This deltaTime's Datatype is : float.</param>
        /// <returns>void.</returns>
        public void LateUpdate(float deltaTime)
        {
            if (!IsEnabled || !IsInitialized) return;
        }



        /// <summary>
        ///  Function Name :  Render.
        /// </summary>
        /// <returns>void.</returns>
        public void Render()
        {
            if (!IsEnabled || !IsInitialized) return;
        }



        /// <summary>
        ///  Function Name :  Enable.
        /// </summary>
        /// <returns>void.</returns>
        public void Enable()
        {
            IsEnabled = true;
            ModernLoggingSystem.Log("INFO", "AnimationSystem: System enabled");
        }



        /// <summary>
        ///  Function Name :  Disable.
        /// </summary>
        /// <returns>void.</returns>
        public void Disable()
        {
            IsEnabled = false;
            ModernLoggingSystem.Log("INFO", "AnimationSystem: System disabled");
        }



        /// <summary>
        ///  Function Name :  Toggle.
        /// </summary>
        /// <returns>void.</returns>
        public void Toggle()
        {
            IsEnabled = !IsEnabled;
            ModernLoggingSystem.Log("INFO", $"AnimationSystem: System {(IsEnabled ? "enabled" : "disabled")}");
        }



        /// <summary>
        ///  Function Name :  Destroy.
        /// </summary>
        /// <returns>void.</returns>
        public void Destroy()
        {
            _animationControllers.Clear();
            _stateMachines.Clear();
            IsEnabled = false;
            IsInitialized = false;
            ModernLoggingSystem.Log("INFO", "AnimationSystem: System destroyed");
        }



        /// <summary>
        ///  Function Name :  Reset.
        /// </summary>
        /// <returns>void.</returns>
        public void Reset()
        {
            _animationControllers.Clear();
            _stateMachines.Clear();
            _entitiesProcessed = 0;
            _totalAnimationTime = 0f;
            UpdateCount = 0;
            LastUpdateTime = 0f;
            ModernLoggingSystem.Log("INFO", "AnimationSystem: System reset");
        }
    }
}









